import { createAgentUIStreamResponse, generateId } from "ai";
import { NextResponse } from "next/server";

import { resumeTailorAgent, type ResumeTailorAgentUIMessage } from "@/ai/agent";
import { checkAuth } from "@/lib/auth-check";
import { upsertMessage, loadChat } from "@/lib/db/tailoring-chat";

// Allow streaming responses up to 60 seconds
export const maxDuration = 60;

export async function POST(request: Request) {
  try {
    const session = await checkAuth();
    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const {
      message,
      chatId,
    }: {
      message: ResumeTailorAgentUIMessage;
      chatId: string;
    } = await request.json();

    // Save the incoming message (user or assistant with tool result)
    await upsertMessage({ chatId, id: message.id, message });

    // Load full message history from database
    const messages = await loadChat(chatId);

    return createAgentUIStreamResponse({
      agent: resumeTailorAgent,
      uiMessages: messages,
      generateMessageId: generateId,
      onFinish: async ({ responseMessage }) => {
        try {
          // Persist the assistant's response (ID is now generated by generateMessageId)
          await upsertMessage({
            chatId,
            id: responseMessage.id,
            message: responseMessage,
          });
        } catch (error) {
          console.error("Failed to persist response message:", error);
          console.error("Response message:", responseMessage);
        }
      },
    });
  } catch (error) {
    console.error("Resume tailor error:", error);
    return NextResponse.json(
      { error: "Failed to process tailor request" },
      { status: 500 }
    );
  }
}
